//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.language", typeof(language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claim Your character, view others etc..
        /// </summary>
        public static string HomeCol1Text {
            get {
                return ResourceManager.GetString("HomeCol1Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Characters.
        /// </summary>
        public static string HomeCol1Title {
            get {
                return ResourceManager.GetString("HomeCol1Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the interactive map to get information about the world.
        /// </summary>
        public static string HomeCol2Text {
            get {
                return ResourceManager.GetString("HomeCol2Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interactive Map.
        /// </summary>
        public static string HomeCol2Title {
            get {
                return ResourceManager.GetString("HomeCol2Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View the in world lore and learn more about Kaldashia.
        /// </summary>
        public static string HomeCol3Text {
            get {
                return ResourceManager.GetString("HomeCol3Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lore.
        /// </summary>
        public static string HomeCol3Title {
            get {
                return ResourceManager.GetString("HomeCol3Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaldashia awaits.
        /// </summary>
        public static string HomeHead {
            get {
                return ResourceManager.GetString("HomeHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Homepage.
        /// </summary>
        public static string HomeHeadTitle {
            get {
                return ResourceManager.GetString("HomeHeadTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse around, claim your character and write adventure logs.
        /// </summary>
        public static string HomeJumbo {
            get {
                return ResourceManager.GetString("HomeJumbo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More Info.
        /// </summary>
        public static string MereInfo {
            get {
                return ResourceManager.GetString("MereInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
